### ISSUE TITLE
Ошибка при подключении мультиварки RMC-M225S

### ISSUE THREAD

**Issue by tanat74** [XNicON/hassio-r4s#11]
Мультиварка RMC-M225S имеет блютуз имя RFS-KMC002 добавил его в константы.
При добавление интеграции, перевожу в сопряжение, но сыпет ошибку.
Подскажите, пожалуйста, в какую сторону копать?

`2024-01-23 23:02:03.183 DEBUG (MainThread) [custom_components.ready4sky.btle] IS CONNECTED: False
2024-01-23 23:02:03.183 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Connecting to device @ D8:20:57:38:0C:63
2024-01-23 23:02:03.185 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Connecting to BlueZ path /org/bluez/hci0/dev_D8_20_57_38_0C_63
2024-01-23 23:02:13.185 DEBUG (MainThread) [bleak.backends.bluezdbus.client] _cleanup_all(/org/bluez/hci0/dev_D8_20_57_38_0C_63)
2024-01-23 23:02:13.186 ERROR (MainThread) [custom_components.ready4sky.btle] Unable to connect
2024-01-23 23:02:13.186 ERROR (MainThread) [custom_components.ready4sky.btle] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 375, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ready4sky/btle.py", line 70, in __aenter__
    await self._conn.connect()
  File "/usr/local/lib/python3.11/site-packages/habluetooth/wrappers.py", line 295, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
2024-01-23 23:02:15.191 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Disconnecting ({/org/bluez/hci0/dev_D8_20_57_38_0C_63})
2024-01-23 23:02:15.192 DEBUG (MainThread) [bleak.backends.bluezdbus.client] already disconnected ({/org/bluez/hci0/dev_D8_20_57_38_0C_63})
2024-01-23 23:02:15.192 ERROR (MainThread) [custom_components.ready4sky] Connect to D8:20:57:38:0C:63 failed
2024-01-23 23:02:15.192 ERROR (MainThread) [custom_components.ready4sky] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 375, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ready4sky/__init__.py", line 74, in async_setup_entry
    await kettler.firstConnect()
  File "/config/custom_components/ready4sky/__init__.py", line 541, in firstConnect
    async with self._conn as conn:
  File "/config/custom_components/ready4sky/btle.py", line 82, in __aenter__
    raise ex
  File "/config/custom_components/ready4sky/btle.py", line 70, in __aenter__
    await self._conn.connect()
  File "/usr/local/lib/python3.11/site-packages/habluetooth/wrappers.py", line 295, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError`

**Comment by XNicON** [comment]
Судя по ошибке TimeoutError, на уровне ОС не может приконнектить мутиварку, 10 сек таймаут коннекта, и за это время не удаётся подключиться.

1) попробовать просто близко поставить её для начала
2) попробовать где HA установлен в ОС, через терминал поискать саму мультиварку в сети и попробовать приконектится руками (пакет bluez-tools)
```
bluetoothctl
[]: scan on
[]: devices
[]: connect D8:20:57:38:0C:63
```
потом попробовать снова передобавить интеграцию

**Comment by tanat74** [comment]
Спасибо! Вероятно у меня какие то глюки. 
Развернул отдельный HA на другом компьютере и смог подключиться.
Переткнул адаптер обратно и смог подключить в терминале с энной попытки, а затем и через интерфейс.

Осталось научиться в интерфейс. Вряд ли жена будет вызывать службу)

**Comment by XNicON** [comment]
Так а в целом более-менее ок всё в компонентах?
Какую строчку в константы добавляли?

RFS-KMC002: 5 ?
Чтоб и мне добавить

**Comment by tanat74** [comment]
Да, программы запускает. Из особенностей: раньше писал при отложенном время до полного завершения (с готовкой). Сейчас только время отложенного, а с запуском программы отдельно время готовки.
Строка в константы: 
`   'RFS-KMC002': 5, # RMC-M225S`

**Comment by XNicON** [comment]
А "раньше" - это когда-то давно были попытки использовать это интеграцию?

**Comment by tanat74** [comment]
Нет, речь про управление с телефона штатной программой.
Так же использовал шлюз на базе esphome (KomX/ESPHome-Ready4Sky), там тоже было сложенное время.
