### ISSUE TITLE
Не подключается чайник G200S

### ISSUE THREAD

**Issue by EugenyOk** [XNicON/hassio-r4s#5]
Здравствуйте!

Не удается подключить чайник G200S (прошивка 4.21).

Интеграция добавляется без девайса, в логах ошибка

```
Logger: homeassistant.config_entries
Source: components/system_log/__init__.py:96
First occurred: 9:22:08 PM (2 occurrences)
Last logged: 9:25:45 PM

Error setting up entry F1:FB:63:C2:BE:30 for ready4sky
Traceback (most recent call last):
  File "/config/custom_components/ready4sky/__init__.py", line 62, in async_setup_entry
    await kettler.firstConnect()
  File "/config/custom_components/ready4sky/__init__.py", line 530, in firstConnect
    async with self._conn as conn:
  File "/config/custom_components/ready4sky/btle.py", line 81, in __aenter__
    raise ex
  File "/config/custom_components/ready4sky/btle.py", line 69, in __aenter__
    await self._conn.connect()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/models.py", line 291, in connect
    return await super().connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 392, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 179, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] le-connection-abort-by-local

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ready4sky/__init__.py", line 64, in async_setup_entry
    _LOGGER.error("Connect to %s through device %s failed", mac)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 179, in emit
    entry = LogEntry(
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 96, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
```

Из нескольких десятков попыток несколько раз устройство все же добавлялось, и даже работало, но переставало сразу же после перезагрузки НА или через некоторое время.

HomeAssistant 2022.10.1 на raspberry pi 4

**Comment by XNicON** [comment]
Похоже проблема не в интеграции а в системе или настройках bluez
тут только гугл в помощь насчёт ошибки "**le-connection-abort-by-local**"

И спасибо, поправил вот этот момент.
Тут текст ошибки просто не правильно формируется.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ready4sky/__init__.py", line 64, in async_setup_entry
    _LOGGER.error("Connect to %s through device %s failed", mac)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 179, in emit
    entry = LogEntry(
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 96, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
```
